### ISSUE TITLE
Napari Problems

### ISSUE THREAD

**Issue by kayjuen** [DeepLabCut/napari-deeplabcut#146]
Hi,
I am working with deeplabcut 3.0.5rc on windows 11.
When I try to "save selected layers" after annotation in npari (gui), I receive the following:
(dlc_test) C:\Windows\System32>python -m deeplabcut
Loading DLC 3.0.0rc5...
Starting GUI...
QPixmap::scaled: Pixmap is a null pixmap
WARNING: DirectWrite: CreateFontFaceFromHDC() failed (Gibt einen Fehler in einer Eingabedatei an, zum Beispiel eine Schriftartdatei.) for QFontDef(Family="MS Sans Serif", pointsize=12, pixelsize=16, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("MS Sans Serif", lfWidth=0, lfHeight=-16) dpi=96
WARNING:vispy:DirectWrite: CreateFontFaceFromHDC() failed (Gibt einen Fehler in einer Eingabedatei an, zum Beispiel eine Schriftartdatei.) for QFontDef(Family="MS Sans Serif", pointsize=12, pixelsize=16, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("MS Sans Serif", lfWidth=0, lfHeight=-16) dpi=96
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\dlc_test\lib\site-packages\napari_deeplabcut\_widgets.py", line 656, in <lambda>
    lambda: _save_layers_dialog(
  File "C:\ProgramData\anaconda3\envs\dlc_test\lib\site-packages\napari_deeplabcut\_widgets.py", line 300, in _save_layers_dialog
    self.viewer.layers.save("", selected=True, plugin="napari-deeplabcut")
  File "C:\ProgramData\anaconda3\envs\dlc_test\lib\site-packages\napari\utils\_proxies.py", line 188, in __call__
    return self.create(self.__wrapped__(*args, **kwargs))
  File "C:\ProgramData\anaconda3\envs\dlc_test\lib\site-packages\napari\components\layerlist.py", line 476, in save
    return save_layers(path, layers, plugin=plugin, _writer=_writer)
  File "C:\ProgramData\anaconda3\envs\dlc_test\lib\site-packages\napari\plugins\io.py", line 229, in save_layers
    _written, writer_name = _write_single_layer_with_plugins(
  File "C:\ProgramData\anaconda3\envs\dlc_test\lib\site-packages\napari\plugins\io.py", line 460, in _write_single_layer_with_plugins
    raise ValueError(
ValueError: There is no registered plugin named 'napari-deeplabcut'.
Plugins capable of writing layer._type_string layers are: set()

Conda list yields the following installations:
napari                    0.4.18                   pypi_0    pypi
napari-console            0.1.0                    pypi_0    pypi
napari-deeplabcut         0.2.1.7                  pypi_0    pypi
napari-plugin-engine      0.2.0                    pypi_0    pypi
napari-svg                0.2.0                    pypi_0    pypi

I simply dont know what to do, since the functions worked fine until a couple of days ago. SInce then I am not able to save annotations. In the respective folder I see a "collecteddata_k.h5" file, but no .csv as it used to be. Moreover, I cant build a skeleton in deeplabcut gui because of missing or non readable .h5 files. 
Has anyone a clue what went wrong on my system?

Best
Kay

**Comment by alexander-vass** [comment]
bump. I have the same exact error and it's killing me. The versions all seem to check out with whats listed on (https://www.napari-hub.org/plugins/napari-deeplabcut) but I cannot for the life of me get the plugin to be recognized. 

in ipython:
`import napari
from napari.plugins import plugin_manager
plugin_manager.discover()
print(plugin_manager.plugins)` 

returns an empty dict. But weirder still, in the napari viewer, whether opened through napari.Viewer() or through deeplabcut via the label_frames call, I can see the keypoint in the plugins dropdown + in the install/uininstall plugins window with the correct version (0.2.1.7).

Additionally, if I try:

`import napari_deeplabcut
print(napari_deeplabcut.__file__)`

I get "C:\Users\DLC_analysis\src\napari-deeplabcut\__init__.py" so, the file appears to be there? Not sure why it can't get registered. Attempting to manually register via: plugin_manager.register(napari_deeplabcut, name="napari-deeplabcut") 
results in the following error: RuntimeError: Refusing to import PyQT5 because PySide6.QtCore is already imported

This is a very bothersome issue and I'm out of ideas after banging my head against a wall for the last few hours, any help would be massively appreciated

**Comment by alexander-vass** [comment]
oh my god I fixed it with the help of a comment I found in a different issue thread, the issue is so dumb I swear

https://github.com/DeepLabCut/DeepLabCut/issues/2627

this comment by [lomedi](https://github.com/lomedi) solved it for me:

"I somehow got the napari plugin to work through rewriting the body parts in the current config file manually, instead of copying and pasting the list of body parts from other config files I used. It seemed that this resolved the error in two separate instances on different computers, so I would recommend trying it to anyone experiencing the same error. I apologize for the delayed update here, and thank you for your support!"

I hope it works for you too

**Comment by C-Achard** [comment]
Hello, thanks for the report and workarounds.

Given the recent dependency updates in both this plugin and DLC, I’m going to close this issue for now as not reproducible on the supported stack.
From the discussion above, this looks like it was tied to an older napari setup (0.4.18) together with plugin-registration issues and a mixed Qt-binding state (`PySide6` already imported, then `PyQt5` attempted later), leading to the plugin not being properly loaded.

Since we have recently upgraded dependency management across repos, this hopefully should not occur anymore as long as PySide6 is used consistently in the env. The newest versions should overall allow for easier installs, compared to previously.

For anyone landing here later, the most useful checks are:
1. Make sure you are using a currently supported napari & plugin version,
2. Make sure the environment is **PySide6-only** (by installing DLC[gui] and/or the plugin, and avoiding installing napari[all])

If anyone is still able to reproduce this on a recent, supported environment, please feel free to comment with updated env details and I will take another look!

Best,
Cyril
