### ISSUE TITLE
Installation: Missing `PyQt5` package

### ISSUE THREAD

**Issue by stes** [DeepLabCut/napari-deeplabcut#44]
I installed the plugin as follows:

``` python
conda create -n napari python==3.8
conda activate napari
pip install napari-deeplabcut
```

which gives the error

```bash
napari

Traceback (most recent call last):
  File "/home/stes/.conda/envs/napari/bin/napari", line 8, in <module>
    sys.exit(main())
  File "/home/stes/.conda/envs/napari/lib/python3.8/site-packages/napari/__main__.py", line 446, in main
    _run()
  File "/home/stes/.conda/envs/napari/lib/python3.8/site-packages/napari/__main__.py", line 299, in _run
    from napari._qt.widgets.qt_splash_screen import NapariSplashScreen
  File "/home/stes/.conda/envs/napari/lib/python3.8/site-packages/napari/_qt/__init__.py", line 9, in <module>
    from qtpy import API_NAME, QtCore
  File "/home/stes/.conda/envs/napari/lib/python3.8/site-packages/qtpy/QtCore.py", line 15, in <module>
    from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5'
```

--> The setup instructions in the README should be updated in this regard.

This can be fixed by simply running

```
pip install PyQt5
```

on my machine. Should this

- become a dependency of this package?
- should we update the README accordingly?

**Comment by jeylau** [comment]
What if you `pip install pyside2` before `pip install napari-deeplabcut`? We don't use pyqt5, and it looks to me like qtpy fails to resolve what framework it should default to use.
