### ISSUE TITLE
Copying labels from one frame to another in napari

### ISSUE THREAD

**Issue by MilanB11** [DeepLabCut/napari-deeplabcut#72]
Hello, I am having problems to copy several labels from one frame to another using the new napari based labeling gui. I am trying to select the labels and copy-paste (ctrl-c, ctrl-v) some of the labels (of static objects) for all the frames in a video but even though single points can sometimes be copied to a different layer, it mostly does not work. Is there maybe another way to do this correctly?
I am using the newest version of DLC on Windows 10 without a GPU (just to label the frames).

Thanks a lot already for your help!
Milan

This is the error message I get when trying to copy the labels:

Traceback (most recent call last):
  File "C:\Users\...\anaconda3\envs\DEEPLABCUT\lib\site-packages\vispy\app\backends\_qt.py", line 561, in keyPressEvent
    self._keyEvent(self._vispy_canvas.events.key_press, ev)
  File "C:\Users\...\anaconda3\envs\DEEPLABCUT\lib\site-packages\vispy\app\backends\_qt.py", line 622, in _keyEvent
    func(native=ev, key=key, text=str(ev.text()), modifiers=mod)
  File "C:\Users\...\anaconda3\envs\DEEPLABCUT\lib\site-packages\vispy\util\event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "C:\Users\...\anaconda3\envs\DEEPLABCUT\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "C:\Users\...\anaconda3\envs\DEEPLABCUT\lib\site-packages\vispy\util\event.py", line 469, in _invoke_callback
    cb(event)
  File "C:\Users\...\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\utils\key_bindings.py", line 545, in on_key_press
    self.press_key(combo)
  File "C:\Users\...\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\utils\key_bindings.py", line 470, in press_key
    generator_or_callback = func()
  File "C:\Users\...\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\layers\points\_points_key_bindings.py", line 64, in copy
    layer._copy_data()
  File "C:\Users\...\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\layers\points\points.py", line 1976, in _copy_data
    'text': self.text._copy(index),
  File "C:\Users\...\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\layers\utils\text_manager.py", line 215, in _copy
    'color': _get_style_values(self.color, indices),
  File "C:\Users\...\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\layers\utils\style_encoding.py", line 289, in _get_style_values
    return values if values.ndim == value_ndim else values[indices]
IndexError: index 4 is out of bounds for axis 0 with size 4

**Comment by jeylau** [comment]
Hi @MilanB11, this feature is not supported currently; I had opened this issue #2, but haven't worked on it yet.
